[package]
name = "pin-box-1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.1", features = ["full"] }
crossterm = { version = "0.27.0", features = ["event-stream"] }
serial_test = "3.1.1"
