[package]
name = "serde-plist-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = { version = "1.6.1", features = ["serde"] }
serde = "1.0.199"
